"""
AI Enrichment Layer

Replaces static security rule recommendations with context-aware insights
generated by OpenAI's GPT-4o mini model.

One API call is made per FindingGroup (not per individual occurrence), keeping
cost low and producing recommendations that cover all affected locations at once.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
from typing import List

from backend.models import FindingGroup

logger = logging.getLogger(__name__)

# ── Excerpt Extractor ─────────────

_HTTP_METHODS = {"get", "post", "put", "delete", "patch", "options", "head", "trace"}


def _extract_excerpt(spec: dict, location: str) -> str:
    """
    Extract the minimal spec subset relevant to a given location path.
    Capped at 2000 chars so prompts stay tightly contained.
    """
    # Strip parenthetical annotations e.g. "(in: query, name: password)"
    clean = re.sub(r"\s*\(.*?\)", "", location).strip()

    excerpt: object = {}

    try:
        if clean.startswith("paths"):
            paths = spec.get("paths", {})
            matched_path = None
            for path_key in paths:
                if clean.startswith(f"paths.{path_key}"):
                    matched_path = path_key
                    break

            if matched_path:
                path_item = paths[matched_path]
                remainder = clean[len(f"paths.{matched_path}"):]
                if remainder.startswith("."):
                    method = remainder[1:].split(".")[0].lower()
                    if method in _HTTP_METHODS and method in path_item:
                        excerpt = {matched_path: {method: path_item[method]}}
                    else:
                        excerpt = {matched_path: path_item}
                else:
                    excerpt = {matched_path: path_item}
            else:
                excerpt = {"paths": dict(list(paths.items())[:3])}

        elif clean.startswith("components"):
            excerpt = spec.get("components", {})
        elif clean.startswith("securityDefinitions"):
            excerpt = spec.get("securityDefinitions", {})
        elif clean.startswith("servers"):
            excerpt = {"servers": spec.get("servers", [])}
        elif clean.startswith("schemes") or clean.startswith("host"):
            excerpt = {
                "schemes":  spec.get("schemes", []),
                "host":     spec.get("host", ""),
                "basePath": spec.get("basePath", "/"),
            }
        else:
            excerpt = {k: v for k, v in spec.items() if k != "paths"}
    except Exception:
        excerpt = {}

    try:
        text = json.dumps(excerpt, indent=2, default=str)
    except Exception:
        text = "{}"

    if len(text) > 2000:
        text = text[:2000] + "\n... (truncated)"
    return text


# ── Prompt Builder ─────────────

_PROMPT_TEMPLATE = """\
You are a friendly security mentor helping a developer understand and fix a \
security issue in their API. Write in plain English — avoid jargon, and explain \
things as if the developer is smart but not a security specialist.

Rule: {rule_name} ({rule_id})
Severity: {severity}
Issue: {description}

Affected locations in their spec ({count} occurrence(s)):
{locations_text}

Relevant part of their API spec (showing the first affected location):
```json
{excerpt}
```

Reply with exactly three short paragraphs using these headings:

**What's happening:** One sentence explaining the specific problem, mentioning \
the actual affected paths or field names.

**Why it matters:** One or two sentences explaining the real-world risk in \
plain terms — what could an attacker actually do?

**How to fix it:** Two or three sentences giving a concrete, copy-pasteable \
fix for this specific API. Show a YAML/JSON snippet or exact field to add/change \
where helpful.

Do not add any text before or after these three paragraphs."""


def _build_prompt(group: FindingGroup, excerpt: str) -> str:
    # List up to 8 locations
    locations_text = "\n".join(
        f"  - {occ.location}" for occ in group.occurrences[:8]
    )
    if group.count > 8:
        locations_text += f"\n  ... and {group.count - 8} more"

    return _PROMPT_TEMPLATE.format(
        rule_name      = group.rule_name,
        rule_id        = group.rule_id,
        severity       = group.severity.value.upper(),
        description    = group.description,
        count          = group.count,
        locations_text = locations_text,
        excerpt        = excerpt,
    )


# ── Enrichment Function ─────────────

async def _enrich_one(
    client,
    spec: dict,
    group: FindingGroup,
    sem: asyncio.Semaphore,
) -> FindingGroup:
    async with sem:
        try:
            # Use the first occurrence's location to pull the relevant spec excerpt
            first_location = group.occurrences[0].location if group.occurrences else ""
            excerpt = _extract_excerpt(spec, first_location)
            prompt  = _build_prompt(group, excerpt)

            response = await client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                max_tokens=500,
                temperature=0.4,
            )
            ai_text = response.choices[0].message.content.strip()

            if ai_text:
                return group.model_copy(update={"recommendation": ai_text + " [AI]"})

        except Exception as e:
            # Re-raise rate limit errors so the batch runner can apply backoff
            if "429" in str(e) or "rate limit" in str(e).lower():
                raise e
            # Any other error (bad key format, network blip, etc.) — log and
            # fall through to return the original group with static recommendation.
            logger.warning(
                "Failed to enrich group %s (%s): %s: %s",
                group.rule_id, group.rule_name, type(e).__name__, e,
            )

    return group


# ── Public Entry Point ─────────────

async def enrich_findings(spec: dict, groups: List[FindingGroup]) -> List[FindingGroup]:
    """
    Replace the ``recommendation`` field of each FindingGroup with a context-aware
    recommendation generated by GPT-4o mini.

    One API call is made per group (not per occurrence), so a rule that fires
    on 50 endpoints still only costs one LLM call.
    """
    if not groups:
        return groups

    try:
        from openai import AsyncOpenAI, RateLimitError
    except ImportError as exc:
        raise ImportError(
            "openai package is required for AI enrichment. "
            "Install it with: pip install openai"
        ) from exc

    api_key = os.environ.get("OPENAI_API_KEY", "")
    if not api_key:
        raise ValueError("OPENAI_API_KEY environment variable is not set.")

    client = AsyncOpenAI(api_key=api_key)

    BATCH_SIZE = 3
    DELAY_BETWEEN_BATCHES = 1

    results = []

    for i in range(0, len(groups), BATCH_SIZE):
        batch = groups[i:i + BATCH_SIZE]
        sem = asyncio.Semaphore(BATCH_SIZE)

        max_retries = 3
        base_delay = 5

        for attempt in range(max_retries):
            try:
                tasks = [_enrich_one(client, spec, g, sem) for g in batch]
                batch_results = await asyncio.gather(*tasks)
                results.extend(batch_results)
                break

            except RateLimitError as e:
                if attempt == max_retries - 1:
                    logger.warning(
                        "Rate limit exhausted after %d attempt(s) for batch at index %d "
                        "— falling back to static recommendations for this batch",
                        max_retries, i,
                    )
                    results.extend(batch)
                    break
                delay = base_delay * (2 ** attempt)
                logger.info(
                    "Rate limited on batch %d, retrying in %ds (attempt %d/%d)",
                    i // BATCH_SIZE + 1, delay, attempt + 1, max_retries,
                )
                await asyncio.sleep(delay)

        if i + BATCH_SIZE < len(groups):
            await asyncio.sleep(DELAY_BETWEEN_BATCHES)

    return results
